export const ADD_RECORDED_VIDEO = 'ADD_VIDEO';

export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_CONTENT = 'SET_CONTENT';
export const SET_STEPS = 'SET_STEPS';

export const ADD_CACHED_VIDEO_PATH = 'ADD_CACHED_VIDEO_PATH';
